apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: hello
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: backend
    spec:
      containers:
        - name: api
          image: "public.ecr.aws/d2n1k8i8/assessment132:api"
          ports:
            - name: http
              containerPort: 9093
          env:
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: creds
                  key: MONGODB_USER
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: creds
                  key: MONGODB_PASSWORD
            - name: HTTP_PORT
              value: "9093"
          resources:
            limits:
              cpu: "100m"
              memory: 256Mi
            requests:
              cpu: "10m"
              memory: 64Mi
          readinessProbe:
            successThreshold: 1
            failureThreshold: 2
            periodSeconds: 5
            initialDelaySeconds: 5
            httpGet:
              path: /ping
              port: 9093
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /health
              port: 9093
            initialDelaySeconds: 3
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  selector:
    app: hello
    tier: backend
  ports:
  - protocol: TCP
    port: 9093
    targetPort: http

# kubectl apply -f api.yaml