apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob
  namespace: bobspace
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bob-full-access
  namespace: bobspace
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bobspace-view
  namespace: bobspace
subjects:
- kind: ServiceAccount
  name: bob
  namespace: bobspace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bob-full-access

# kubectl create -f serviceAccount.yaml